<div x-data="{ toastMsg: '', toastType: '', showAddProductModal: false }"
    @toast.window="toastMsg = $event.detail.message; toastType = $event.detail.type; setTimeout(() => toastMsg = '', 3000)">

    {{-- TOAST --}}
    <div x-show="toastMsg" x-transition :class="toastType === 'success' ? 'bg-green-500' : 'bg-red-500'"
        class="fixed top-5 right-5 z-50 text-white px-4 py-2 rounded shadow-lg text-sm">
        <span x-text="toastMsg"></span>
    </div>

    {{-- FILTER BAR --}}
    <div
        class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 my-4 dark:bg-zinc-900">
        <p class="dark:text-white text-base font-semibold">Data Tabel Unit of Measure (UOM)</p>
        <div class="flex flex-col sm:flex-row items-center gap-3 w-full md:w-auto">
            <div class="relative w-full sm:w-72">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg aria-hidden="true" class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clip-rule="evenodd" />
                    </svg>
                </div>
                <input wire:model.live.debounce.300ms="search" type="text"
                    class="dark:bg-zinc-800 border border-gray-600 dark:text-white text-sm rounded-lg block w-full pl-10 p-2.5 placeholder-gray-400"
                    placeholder="Cari kode, nama..." />
            </div>
            <select wire:model.live="perPage"
                class="dark:bg-zinc-800 border border-gray-600 dark:text-white text-sm rounded-lg px-8 py-2.5 w-full sm:w-auto">
                <option value="10">10 / hal</option>
                <option value="25">25 / hal</option>
                <option value="50">50 / hal</option>
            </select>
            <label class="flex items-center gap-2 text-sm dark:text-gray-300 cursor-pointer whitespace-nowrap">
                <input type="checkbox" wire:model.live="showTrashed"
                    class="w-4 h-4 rounded border-gray-600 dark:bg-zinc-800 text-blue-600">
                Tampilkan Terhapus
            </label>
            <button wire:click="openCreate"
                class="inline-flex items-center gap-2 text-white bg-blue-600 hover:bg-blue-700 text-sm font-medium px-4 py-2.5 rounded-lg whitespace-nowrap cursor-pointer sm:w-auto w-full justify-center">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
                Tambah Data
            </button>
        </div>
    </div>

    {{-- CREATE / EDIT MODAL --}}
    @if ($showModal)
        <div class="fixed inset-0 z-40 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
            <div class="bg-white dark:bg-zinc-800 rounded-2xl shadow-xl w-full max-w-7xl mx-auto max-h-[80vh] flex flex-col overflow-hidden">

                <div
                    class="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-zinc-700 shrink-0 bg-zinc-50 dark:bg-zinc-900">
                    <h3 class="text-lg font-semibold dark:text-white">
                        Transfer Stock
                    </h3>
                    <button wire:click="$set('showModal', false)"
                        class="text-gray-400 hover:text-white cursor-pointer">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div class="flex-1 overflow-y-auto px-6 py-5">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label class="block mb-1 text-sm font-medium dark:text-white">ADI No</label>
                            <input wire:model.defer="adi_no" type="text" disabled placeholder="autogenerated"
                                class="bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-zinc-800 dark:border-gray-600 dark:text-white border-gray-300" />
                        </div>

                        <div>
                            <label class="block mb-1 text-sm font-medium dark:text-white">Date</label>
                            <input wire:model="date" type="date"
                                class="bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-zinc-800 dark:border-gray-600 dark:text-white border-gray-300" />
                        </div>

                        <div>
                            <label class="block mb-1 text-sm font-medium dark:text-white">Warehouse</label>
                            <select wire:model="warehouse"
                                class="bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-zinc-800 dark:border-gray-600 dark:text-white border-gray-300">
                                <option value="">Pilih Gudang</option>
                                <option value="1">Main Warehouse</option>
                                <option value="2">Secondary Warehouse</option>
                            </select>
                        </div>

                        <div>
                            <label class="block mb-1 text-sm font-medium dark:text-white">Notes</label>
                            <input wire:model="notes" type="text"
                                class="bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-zinc-800 dark:border-gray-600 dark:text-white border-gray-300"
                                placeholder="Keterangan tambahan..." />
                        </div>
                    </div>

                    <div class="overflow-x-auto mt-6">
                            <table
                                class="w-full text-base text-left text-gray-900 dark:text-white border-collapse border border-gray-300 dark:border-zinc-600 min-w-max whitespace-nowrap">
                                <thead
                                    class="text-sm font-bold text-gray-900 uppercase bg-gray-200 dark:bg-zinc-700 dark:text-white">
                                    <tr>
                                        <th
                                            class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-center w-14">
                                            <button type="button" @click="showAddProductModal = true"
                                                class="inline-flex items-center justify-center w-10 h-10 rounded-sm bg-blue-600 text-white hover:bg-blue-700">
                                                <span class="text-xl font-semibold">+</span>
                                            </button>
                                        </th>
                                        <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-sm">Kode
                                            Produk</th>
                                        <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-sm">Nama
                                            Produk</th>
                                        <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-sm">Qty</th>
                                        <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-sm">UOM</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <tr class="hover:bg-gray-100 dark:hover:bg-zinc-800 text-sm">
                                            <td
                                                class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-center">
                                                <button type="button"
                                                    class="text-red-500 hover:text-red-700">
                                                    <svg class="w-4 h-4" fill="none" stroke="currentColor"
                                                        viewBox="0 0 24 24">
                                                        <path stroke-linecap="round" stroke-linejoin="round"
                                                            stroke-width="2"
                                                            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                    </svg>
                                                </button>
                                            </td>
                                            <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">
                                                PRD-001</td>
                                            <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">
                                                Produk Satu</td>
                                            <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">
                                                <input type="number" min="1" value="1"
                                                    class="bg-gray-50 border border-gray-300 text-gray-900 text-xs rounded-lg block w-24 p-2 dark:bg-zinc-800 dark:border-gray-600 dark:text-white"
                                                    placeholder="Qty" />
                                            </td>
                                            <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">
                                                <select
                                                    class="bg-gray-50 border border-gray-300 text-gray-900 text-xs rounded-lg block w-36 p-2 dark:bg-zinc-800 dark:border-gray-600 dark:text-white">
                                                        <option value="">Pilih Satuan</option>
                                                        <option value="pcs">Pcs</option>
                                                        <option value="box">Box</option>
                                                        <option value="kg">Kg</option>
                                                </select>
                                            </td>
                                        </tr>
                                </tbody>
                            </table>
                        </div>

                        <div x-show="showAddProductModal" x-cloak
                            class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                            <div class="bg-white dark:bg-zinc-900 rounded-2xl shadow-xl w-full max-w-4xl mx-auto max-h-[85vh] overflow-hidden">
                                <div class="flex items-start justify-between px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-900">
                                    <div>
                                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Tambah Detail Produk</h3>
                                        <p class="mt-1 text-sm text-gray-600 dark:text-gray-300">Cari produk dan pilih dari daftar.</p>
                                    </div>
                                    <button type="button" @click="showAddProductModal = false"
                                        class="text-gray-500 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                        </svg>
                                    </button>
                                </div>

                                <div class="p-6 space-y-6">
                                    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                                        <div>
                                            <label class="block mb-2 text-sm font-medium text-gray-700 dark:text-gray-200">Cari Produk</label>
                                            <input type="text" placeholder="Cari kode atau nama produk"
                                                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-3 dark:bg-zinc-800 dark:border-gray-600 dark:text-white" />
                                        </div>
                                        <div>
                                            <label class="block mb-2 text-sm font-medium text-gray-700 dark:text-gray-200">Kategori Produk</label>
                                            <select
                                                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-3 dark:bg-zinc-800 dark:border-gray-600 dark:text-white">
                                                <option value="">Semua Kategori</option>
                                                <option value="cat1">Kategori 1</option>
                                                <option value="cat2">Kategori 2</option>
                                                <option value="cat3">Kategori 3</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="overflow-x-auto">
                                        <table class="w-full text-sm text-left text-gray-900 dark:text-white border-collapse border border-gray-300 dark:border-zinc-600">
                                            <thead class="bg-gray-100 dark:bg-zinc-800 text-xs uppercase tracking-wide text-gray-700 dark:text-gray-300">
                                                <tr>
                                                    <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-center">Pilih</th>
                                                    <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Kode</th>
                                                    <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Nama Produk</th>
                                                    <th class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Kategori</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr class="hover:bg-gray-50 dark:hover:bg-zinc-800">
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-center">
                                                        <input type="radio" name="selected_product" class="h-4 w-4 text-blue-600" />
                                                    </td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">PRD-001</td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Produk Satu</td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Kategori A</td>
                                                </tr>
                                                <tr class="hover:bg-gray-50 dark:hover:bg-zinc-800">
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-center">
                                                        <input type="radio" name="selected_product" class="h-4 w-4 text-blue-600" />
                                                    </td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">PRD-002</td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Produk Dua</td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Kategori B</td>
                                                </tr>
                                                <tr class="hover:bg-gray-50 dark:hover:bg-zinc-800">
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3 text-center">
                                                        <input type="radio" name="selected_product" class="h-4 w-4 text-blue-600" />
                                                    </td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">PRD-003</td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Produk Tiga</td>
                                                    <td class="border border-gray-300 dark:border-zinc-600 px-4 py-3">Kategori C</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <div class="flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-900">
                                    <button type="button" @click="showAddProductModal = false"
                                        class="px-4 py-2 text-sm rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-100 dark:border-zinc-700 dark:text-gray-200 dark:hover:bg-zinc-800">
                                        Batal
                                    </button>
                                    <button type="button" @click="showAddProductModal = false"
                                        class="px-4 py-2 text-sm rounded-lg bg-blue-600 text-white hover:bg-blue-700">
                                        Simpan
                                    </button>
                                </div>
                            </div>
                        </div>
                </div>

                <div
                    class="flex justify-end gap-2 p-6 border-t border-gray-200 dark:border-zinc-700 shrink-0 bg-white dark:bg-zinc-900">
                    <button wire:click="$set('showModal', false)"
                        class="px-4 py-2 text-sm rounded-lg border border-gray-600 dark:text-gray-300 hover:bg-zinc-700">
                        Batal
                    </button>
                    <button wire:click="save" wire:loading.attr="disabled"
                        class="px-4 py-2 text-sm rounded-lg bg-blue-600 hover:bg-blue-700 text-white disabled:opacity-50 cursor-pointer">
                        <span wire:loading.remove wire:target="save">Simpan</span>
                        <span wire:loading wire:target="save">Menyimpan...</span>
                    </button>
                </div>
            </div>
        </div>
    @endif
</div>
